project/models.py
from project import db




class ChatRoom(db.Model):

    __tablename__ = 'chatroom'

    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, unique=True)


    def __init__(self, url):
        self.url = url

project/chat/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, IntegerField, validators


class UrlForm(FlaskForm):
    url = StringField('Create Your Room')

project/__init__.py
from flask import Flask, redirect
from flask_socketio import SocketIO
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CsrfProtect
import os

app = Flask(__name__, static_url_path='/static')
CsrfProtect(app)



if os.environ.get('ENV') == 'production':
    debug = False
    # Heroku gives us an environment variable called DATABASE_URL when we add a postgres database
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
else:
    debug = True
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/chat_db'


#app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/chat_db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = "STRING"
app.config['TEMPLATES_AUTO_RELOAD'] = True

db = SQLAlchemy(app)
socketio =  SocketIO(app)


from project.chat.views import chat_blueprint
#This is where you import more blueprints. Don't forget to register them below!


app.register_blueprint(chat_blueprint)

project/chat/views.py
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint
from flask_socketio import SocketIO, send, emit, join_room, leave_room
from project.chat.forms import UrlForm
from project.models import ChatRoom
from project import db, app, socketio







chat_blueprint = Blueprint(
    'chat',
    __name__,
    template_folder = "templates"
)


current_url = ''
@chat_blueprint.route('/', methods=['GET', 'POST'])
def index():

    form = UrlForm(request.form)
    if request.method == 'POST':
        #Query Database to see if url is already in the database. If in database then it is currently in use
        #If it isn't in the database then connect to url and add it to the database so no one else can create the same room
        user_url = ChatRoom(request.form['url'])
        db_url = ChatRoom.query.filter_by(url=user_url.url).first()

        if db_url == None:
            #add new url to database
            url = ChatRoom(user_url.url)
            db.session.add(url)
            db.session.commit()
            #join_room(url)
            return redirect(url_for('chat.chat', user_route=user_url.url))
        else:
            flash("Sorry but that room is currently taken.")
            flash("Please choose another room.")
            return render_template('/chat/index.html', form=form)
    return render_template('/chat/index.html', form=form)

@chat_blueprint.route('/<user_route>')
def chat(user_route):
    #if user_route is in database and user is allowed in room allow the connection
    return render_template('/chat/chat.html')






#SOCKET EVENTS






# Keep track of connected users
class Socket:
    def __init__(self, sid):
        self.sid = sid
        self.connected = True
        self.username = sid
        self.room = sid


sockets = []



@socketio.on('connect')
def add_socket():
    sockets.append(Socket(request.sid))
    print(sockets)
    emit('user_connect', {'data' : 'user connected'})

@socketio.on('join_room')
def join(msg):
    for socket in sockets:
        if socket.sid == request.sid:
            socket.room = msg['room']
    join_room(msg['room'])


@socketio.on('disconnect')
def remove_socket():
    for socket in sockets:
        if socket.sid == request.sid:
            username  = socket.username
            room = socket.room
            sockets.remove(socket)
            print(sockets)
            emit('disconnect', {'data': username}, room=room, broadcast=True)

@socketio.on('username_message')
def handle_username_message(msg):
    for socket in sockets:
        if request.sid == socket.sid:
            socket.username = msg['data']
            username = socket.username
            room = socket.room
            emit('username_message', {'data': msg['data'], 'username': username},room=room, broadcast=True)

@socketio.on('message')
def handle_message(msg):
    username = ''
    guest_name = ''
    for socket in sockets:
        if request.sid == socket.sid:
            username = socket.username
        elif request.sid != socket.sid and socket.room == msg['room']:
            guest_name = socket.username
    emit('message', {'data': msg['data'], 'username': username, 'guest_name': guest_name}, broadcast=True, room=msg['room'])


@socketio.on('move')
def handle_move(msg):
    print(msg['whos_move'])
    emit('move', {'move':msg['move'], 'whos_move': msg['whos_move']}, broadcast=True, room=msg['room'])

@socketio.on('restart')
def handle_restart(msg):
    emit('restart', broadcast=True, room=msg['room'])

project/chat/templates/chat/chat.html
{% extends 'base.html' %} {% block content %}

<div id="header_username_container">
    <i class="fa fa-3x fa-user" aria-hidden="true"></i>
    <div id="header_username"></div>
</div>

<div id="outer_logo_container">
    <div id="logo_container">
        <svg enable-background="new 0 0 100 100" height="40px" version="1.1" viewBox="0 0 100 100" width="40px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="white_exp" />
            <g id="black_exp">
                <path fill="#6a5acd" d="M37,38c0-1.1,0.9-2,2-2h22c1.1,0,2,0.9,2,2s-0.9,2-2,2H39C37.9,40,37,39.1,37,38z M34,84h32c1.1,0,2-0.9,2-2s-0.9-2-2-2H34   c-1.1,0-2,0.9-2,2S32.9,84,34,84z M69,85H31c-2.2,0-4,1.8-4,4s1.8,4,4,4h38c2.2,0,4-1.8,4-4S71.2,85,69,85z M50,35   c7.18,0,13-5.82,13-13S57.18,9,50,9s-13,5.82-13,13S42.82,35,50,35z M58,41H42c0,33.478-4.052,33.959-5.99,38H63.99   C62.052,74.959,58,74.478,58,41z" />
            </g>
        </svg>
        <i class="fa fa-2x fa-comments-o" aria-hidden="true"></i>
        <svg enable-background="new 0 0 100 100" height="40px" version="1.1" viewBox="0 0 100 100" width="40px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="white">
                <path fill="#6a5acd" d="M69.878,83.072C69.954,82.726,70,82.369,70,82c0-2.695-2.148-4.885-4.82-4.982c-0.16-0.265-0.323-0.524-0.489-0.783   c-1.822-2.842-4.552-7.112-4.685-33.235C62.76,42.996,65,40.755,65,38c0-2.707-2.166-4.905-4.853-4.985   C63.122,30.272,65,26.356,65,22c0-8.271-6.729-15-15-15s-15,6.729-15,15c0,4.356,1.878,8.272,4.853,11.015   C37.166,33.095,35,35.293,35,38c0,2.755,2.24,4.996,4.994,5c-0.133,26.124-2.862,30.394-4.685,33.235   c-0.166,0.259-0.329,0.519-0.489,0.783C32.148,77.115,30,79.305,30,82c0,0.369,0.046,0.726,0.122,1.072   C27.229,83.499,25,85.99,25,89c0,3.309,2.691,6,6,6h38c3.309,0,6-2.691,6-6C75,85.99,72.771,83.499,69.878,83.072z M34,82   c0-0.542,0.458-1,1-1h30c0.542,0,1,0.458,1,1s-0.458,1-1,1H35C34.458,83,34,82.542,34,82z M39.535,77   c2.042-3.56,4.339-10.124,4.46-34h12.01c0.121,23.876,2.418,30.44,4.46,34H39.535z M39,22c0-6.065,4.935-11,11-11s11,4.935,11,11   s-4.935,11-11,11S39,28.065,39,22z M39,38c0-0.542,0.458-1,1-1h20c0.542,0,1,0.458,1,1s-0.458,1-1,1H40C39.458,39,39,38.542,39,38z    M69,91H31c-1.103,0-2-0.897-2-2s0.897-2,2-2h38c1.103,0,2,0.897,2,2S70.103,91,69,91z" />
            </g>
            <g id="black" />
        </svg>
    </div>
    <div id="logo_name">
        <h3>Pawn Talk</h3>
    </div>
</div>

<div id=username_overlay>
    <div id="username_input_div">
        <div id="username_input_div_inner">
            <label id="username_label" for="username_input">Create a Username</label>
            <input id="username_input" type="text">
            <button class="button" id="send_username_button">Start</button>
        </div>
    </div>
</div>
<div id=outer_container>
    <div id="inner_container">






        <div id="board_chat_container">
            <div id="game_container">
                <div id="gameBoard"></div>
                <div id="board_button_container">
                    <p id="status"></p>
                    <p id="whos_move">It's white's move</p>
                    <button class="button" type="button" id="startBtn">Restart Game</button>
                    <!--<button class="button" type="button" id="flipBtn">Flip Board</button>-->
                </div>

            </div>
            <div id="messages_container">

                <div id="message_list_div">
                    <div id="guest_name"></div>
                    <ul id="messages"></ul>
                </div>
                <div id="message_input_container">
                    <input placeholder="message" type="text" id="my_message">
                    <button class="button" id="send_button"><i class="fa fa-lg fa-comment-o" aria-hidden="true"></i></button>
                </div>
                <div id="bottom_container">
                    <div id="link"></div>
                    <button class="button" id="copy">Copy Room Link<i class="fa fa-lg fa-clipboard" aria-hidden="true"></i></button>
                </div>
            </div>
        </div>



    </div>

    <div id="credit_div">
        <p>Icon Credit</p>
        <p class="credit_p">https://www.iconfinder.com/colomolo</p>
        <p class="credit_p">http://fontawesome.io/</p>
    </div>

</div>




<script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>

<script src="{{ url_for('static', filename='chessboardjs/js/chessboard-0.3.0.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.10.2/chess.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
<script src="https://use.fontawesome.com/0265280461.js"></script>
<script src="{{ url_for('static', filename='chat.js') }}"></script>
{% endblock %}

project/chat/templates/chat/index.html
{% extends 'base.html' %} {% block content %}
<div id="header">
    <div id="logo_container">
        <svg enable-background="new 0 0 100 100" height="40px" version="1.1" viewBox="0 0 100 100" width="40px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="white_exp" />
            <g id="black_exp">
                <path fill="#6a5acd" d="M37,38c0-1.1,0.9-2,2-2h22c1.1,0,2,0.9,2,2s-0.9,2-2,2H39C37.9,40,37,39.1,37,38z M34,84h32c1.1,0,2-0.9,2-2s-0.9-2-2-2H34   c-1.1,0-2,0.9-2,2S32.9,84,34,84z M69,85H31c-2.2,0-4,1.8-4,4s1.8,4,4,4h38c2.2,0,4-1.8,4-4S71.2,85,69,85z M50,35   c7.18,0,13-5.82,13-13S57.18,9,50,9s-13,5.82-13,13S42.82,35,50,35z M58,41H42c0,33.478-4.052,33.959-5.99,38H63.99   C62.052,74.959,58,74.478,58,41z" />
            </g>
        </svg>
        <i class="fa fa-2x fa-comments-o" aria-hidden="true"></i>
        <svg enable-background="new 0 0 100 100" height="40px" version="1.1" viewBox="0 0 100 100" width="40px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="white">
                <path fill="#6a5acd" d="M69.878,83.072C69.954,82.726,70,82.369,70,82c0-2.695-2.148-4.885-4.82-4.982c-0.16-0.265-0.323-0.524-0.489-0.783   c-1.822-2.842-4.552-7.112-4.685-33.235C62.76,42.996,65,40.755,65,38c0-2.707-2.166-4.905-4.853-4.985   C63.122,30.272,65,26.356,65,22c0-8.271-6.729-15-15-15s-15,6.729-15,15c0,4.356,1.878,8.272,4.853,11.015   C37.166,33.095,35,35.293,35,38c0,2.755,2.24,4.996,4.994,5c-0.133,26.124-2.862,30.394-4.685,33.235   c-0.166,0.259-0.329,0.519-0.489,0.783C32.148,77.115,30,79.305,30,82c0,0.369,0.046,0.726,0.122,1.072   C27.229,83.499,25,85.99,25,89c0,3.309,2.691,6,6,6h38c3.309,0,6-2.691,6-6C75,85.99,72.771,83.499,69.878,83.072z M34,82   c0-0.542,0.458-1,1-1h30c0.542,0,1,0.458,1,1s-0.458,1-1,1H35C34.458,83,34,82.542,34,82z M39.535,77   c2.042-3.56,4.339-10.124,4.46-34h12.01c0.121,23.876,2.418,30.44,4.46,34H39.535z M39,22c0-6.065,4.935-11,11-11s11,4.935,11,11   s-4.935,11-11,11S39,28.065,39,22z M39,38c0-0.542,0.458-1,1-1h20c0.542,0,1,0.458,1,1s-0.458,1-1,1H40C39.458,39,39,38.542,39,38z    M69,91H31c-1.103,0-2-0.897-2-2s0.897-2,2-2h38c1.103,0,2,0.897,2,2S70.103,91,69,91z" />
            </g>
            <g id="black" />
        </svg>
    </div>
    <div id="logo_name">
        <h3>Pawn Talk</h3>
    </div>
</div>
<div id="landing_page_main">
    <div id="landing_page_overlay">
        <div id="url_form_container">
            <form action="{{url_for('chat.index')}}" method="POST">
                {{ form.hidden_tag() }} {% for field in form if field.widget.input_type != 'hidden' %}
                <p>
                    {{ field.label }} {{ field }}
                    <span>
      {% if field.errors %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
                </p>
                {% endfor %}

                <div id="add_url_button_div">
                    {% for message in get_flashed_messages() %}
                    <p>{{ message }}</p>
                    {% endfor %}
                    <button class="button" type="submit">Create Room</button>
                </div>
            </form>
        </div>
        <div id="tagline_div">
            <h3>Want to chat?</h3>
            <h3>And play chess?</h3>
            <h3>We have you covered in Real-Time</h3>
        </div>
    </div>

    <div id="credit_div">
        <p>Icon Credit</p>
        <p class="credit_p">https://www.iconfinder.com/colomolo</p>
        <p class="credit_p">http://fontawesome.io/</p>
    </div>
</div>



<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
<script type="text/javascript">
    document.getElementById("url").focus();
</script>
<script src="https://use.fontawesome.com/0265280461.js"></script>


{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Pawn Talk</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='chessboardjs/css/chessboard-0.3.0.min.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>

<body>

    {% block content %} {% endblock %}


    <!-- <script src="{{ url_for('static', filename='main.js') }}"></script>-->
</body>

</html>